spring.datasource.url=jdbc:mysql://localhost:3306/resumeanalyzer
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=AQ.Ab8RN6KhCLmqbEF809Bx34l68Cn2h-L5pktzsOu7GqBQtJYP0w